-- MySQL Script generated by MySQL Workbench
-- Fri Nov 20 20:22:16 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema CarWashBooking
-- -----------------------------------------------------
-- The main Data Base of the web-site

-- -----------------------------------------------------
-- Schema CarWashBooking
--
-- The main Data Base of the web-site
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CarWashBooking` DEFAULT CHARACTER SET utf8 ;
USE `CarWashBooking` ;

-- -----------------------------------------------------
-- Table `CarWashBooking`.`feedback`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarWashBooking`.`feedback` (
  `id_feedback` INT NOT NULL,
  `car_wash_id_car_wash` INT NULL,
  `user_id_user` INT NULL,
  `booking_id_booking` INT NULL,
  `rank_total` INT NULL,
  `rank_cat1` INT NULL,
  `comment_cat1` MEDIUMTEXT NULL,
  `rank_cat2` INT NULL,
  `comment_cat2` MEDIUMTEXT NULL,
  `rank_cat3` INT NULL,
  `comment_cat3` MEDIUMTEXT NULL,
  `rank_cat4` INT NULL,
  `comment_cat4` MEDIUMTEXT NULL,
  `rank_cat5` INT NULL,
  `comment_cat5` MEDIUMTEXT NULL,
  `rank_cat6` INT NULL,
  `comment_cat6` MEDIUMTEXT NULL,
  `rank_cat7` INT NULL,
  `comment_cat7` MEDIUMTEXT NULL,
  `rank_cat8` INT NULL,
  `comment_cat8` MEDIUMTEXT NULL,
  `rank_cat9` INT NULL,
  `comment_cat9` MEDIUMTEXT NULL,
  `rank_cat10` INT NULL,
  `comment_cat10` MEDIUMTEXT NULL,
  PRIMARY KEY (`id_feedback`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CarWashBooking`.`car_wash`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarWashBooking`.`car_wash` (
  `id_car_wash` INT NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `photo` VARCHAR(45) NULL,
  `adress` VARCHAR(45) NOT NULL,
  `tel_number` INT NULL,
  `main_service_name` VARCHAR(45) NOT NULL,
  `add_service_name` VARCHAR(45) NULL,
  `rank` VARCHAR(45) NULL,
  `service_name` VARCHAR(45) NULL,
  `money_left` INT NOT NULL,
  `booking_id_booking` INT NULL,
  `feedback_id_feedback` INT NULL,
  PRIMARY KEY (`id_car_wash`),
  INDEX `fk_car_wash_booking_idx` (`booking_id_booking` ASC),
  INDEX `fk_car_wash_feedback1_idx` (`feedback_id_feedback` ASC),
  CONSTRAINT `fk_car_wash_booking`
    FOREIGN KEY (`booking_id_booking`)
    REFERENCES `CarWashBooking`.`booking` (`id_booking`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_car_wash_feedback1`
    FOREIGN KEY (`feedback_id_feedback`)
    REFERENCES `CarWashBooking`.`feedback` (`id_feedback`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CarWashBooking`.`payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarWashBooking`.`payment` (
  `id_payment` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(127) NULL,
  `tax_user` FLOAT NOT NULL,
  `tax_site` FLOAT NOT NULL,
  `icon` VARCHAR(45) NULL,
  `user_id_user` INT NOT NULL,
  `car_wash_id_car_wash` INT NOT NULL,
  PRIMARY KEY (`id_payment`),
  INDEX `fk_payments_User1_idx` (`user_id_user` ASC),
  INDEX `fk_payments_car_wash1_idx` (`car_wash_id_car_wash` ASC),
  CONSTRAINT `fk_payments_User1`
    FOREIGN KEY (`user_id_user`)
    REFERENCES `CarWashBooking`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_payments_car_wash1`
    FOREIGN KEY (`car_wash_id_car_wash`)
    REFERENCES `CarWashBooking`.`car_wash` (`id_car_wash`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CarWashBooking`.`booking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarWashBooking`.`booking` (
  `id_booking` INT NOT NULL,
  `id_car_wash` INT NOT NULL,
  `id_user` INT NOT NULL,
  `id_main_service` INT NOT NULL,
  `add_service_name` VARCHAR(45) NULL,
  `payment_method_name` VARCHAR(45) NOT NULL,
  `time_date` DATETIME NOT NULL,
  `time_lenghts` INT NOT NULL,
  `cost` INT NOT NULL,
  `user_car_type` VARCHAR(45) NOT NULL,
  `payments_tax_site` INT NOT NULL,
  `payments_id_payment` INT NULL,
  `feedback_id_feedback` INT NULL,
  PRIMARY KEY (`id_booking`),
  INDEX `fk_booking_payments1_idx` (`payments_id_payment` ASC),
  INDEX `fk_booking_feedback1_idx` (`feedback_id_feedback` ASC),
  CONSTRAINT `fk_booking_payments1`
    FOREIGN KEY (`payments_id_payment`)
    REFERENCES `CarWashBooking`.`payment` (`id_payment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_booking_feedback1`
    FOREIGN KEY (`feedback_id_feedback`)
    REFERENCES `CarWashBooking`.`feedback` (`id_feedback`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CarWashBooking`.`email`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarWashBooking`.`email` (
  `user_id_user` INT NOT NULL,
  `email` VARCHAR(127) NOT NULL,
  `get_email` INT NOT NULL,
  PRIMARY KEY (`user_id_user`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CarWashBooking`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarWashBooking`.`user` (
  `id_user` INT NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `photo` VARCHAR(45) NOT NULL,
  `car_number` INT NOT NULL,
  `tel_number` INT NOT NULL,
  `car_type` VARCHAR(45) NOT NULL,
  `favourites` VARCHAR(45) NOT NULL,
  `add_service_id` VARCHAR(45) NOT NULL,
  `main_service_id` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `booking_id_booking` INT NOT NULL,
  `email_id_user` INT NOT NULL,
  `feedback_id_feedback` INT NOT NULL,
  PRIMARY KEY (`id_user`),
  INDEX `fk_User_booking1_idx` (`booking_id_booking` ASC),
  INDEX `fk_User_email1_idx` (`email_id_user` ASC),
  INDEX `fk_User_feedback1_idx` (`feedback_id_feedback` ASC),
  CONSTRAINT `fk_User_booking1`
    FOREIGN KEY (`booking_id_booking`)
    REFERENCES `CarWashBooking`.`booking` (`id_booking`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_email1`
    FOREIGN KEY (`email_id_user`)
    REFERENCES `CarWashBooking`.`email` (`user_id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_feedback1`
    FOREIGN KEY (`feedback_id_feedback`)
    REFERENCES `CarWashBooking`.`feedback` (`id_feedback`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CarWashBooking`.`main_service_cost`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarWashBooking`.`main_service_cost` (
  `id_main_service` INT NOT NULL,
  `id_car_wash` INT NOT NULL,
  `cost` INT NOT NULL,
  PRIMARY KEY (`id_main_service`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CarWashBooking`.`main_service`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarWashBooking`.`main_service` (
  `id_main_service` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(127) NULL,
  `time_duration` INT NULL,
  `icon` VARCHAR(127) NULL,
  `main_service_id_main_service` INT NULL,
  `booking_id_booking` INT NULL,
  PRIMARY KEY (`id_main_service`),
  INDEX `fk_main_service_main_service_cost1_idx` (`main_service_id_main_service` ASC),
  INDEX `fk_main_service_booking1_idx` (`booking_id_booking` ASC),
  CONSTRAINT `fk_main_service_main_service_cost1`
    FOREIGN KEY (`main_service_id_main_service`)
    REFERENCES `CarWashBooking`.`main_service_cost` (`id_main_service`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_main_service_booking1`
    FOREIGN KEY (`booking_id_booking`)
    REFERENCES `CarWashBooking`.`booking` (`id_booking`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CarWashBooking`.`add_service_cost`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarWashBooking`.`add_service_cost` (
  `id_add_service` INT NOT NULL,
  `id_car_wash` INT NOT NULL,
  `cost` INT NOT NULL,
  PRIMARY KEY (`id_add_service`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CarWashBooking`.`add_service`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarWashBooking`.`add_service` (
  `id_add_service` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(127) NULL,
  `time_duration` INT NULL,
  `icon` VARCHAR(127) NULL,
  `add_service_cost_id_add_service` INT NOT NULL,
  `booking_id_booking` INT NOT NULL,
  PRIMARY KEY (`id_add_service`),
  INDEX `fk_add_service_add_service_cost1_idx` (`add_service_cost_id_add_service` ASC),
  INDEX `fk_add_service_booking1_idx` (`booking_id_booking` ASC),
  CONSTRAINT `fk_add_service_add_service_cost1`
    FOREIGN KEY (`add_service_cost_id_add_service`)
    REFERENCES `CarWashBooking`.`add_service_cost` (`id_add_service`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_add_service_booking1`
    FOREIGN KEY (`booking_id_booking`)
    REFERENCES `CarWashBooking`.`booking` (`id_booking`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CarWashBooking`.`service`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarWashBooking`.`service` (
  `id_service` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `icon` VARCHAR(45) NULL,
  `free` INT NULL,
  `car_wash_id_car_wash` INT NOT NULL,
  PRIMARY KEY (`id_service`),
  INDEX `fk_service_car_wash1_idx` (`car_wash_id_car_wash` ASC),
  CONSTRAINT `fk_service_car_wash1`
    FOREIGN KEY (`car_wash_id_car_wash`)
    REFERENCES `CarWashBooking`.`car_wash` (`id_car_wash`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CarWashBooking`.`deposits`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarWashBooking`.`deposits` (
  `id_deposit` INT NOT NULL,
  `car_wash_id_car_wash` INT NOT NULL,
  `summ` INT NOT NULL,
  `id_payment` INT NOT NULL,
  `date` DATETIME NOT NULL,
  PRIMARY KEY (`id_deposit`),
  INDEX `fk_deposits_car_wash1_idx` (`car_wash_id_car_wash` ASC),
  CONSTRAINT `fk_deposits_car_wash1`
    FOREIGN KEY (`car_wash_id_car_wash`)
    REFERENCES `CarWashBooking`.`car_wash` (`id_car_wash`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CarWashBooking`.`widthdraw`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarWashBooking`.`widthdraw` (
  `id_widthdraw` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(127) NULL,
  `icon` VARCHAR(45) NULL,
  `tax_site` FLOAT NULL,
  PRIMARY KEY (`id_widthdraw`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CarWashBooking`.`calendar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarWashBooking`.`calendar` (
  `car_wash_id_car_wash` INT NOT NULL,
  `booked` DATETIME NOT NULL,
  PRIMARY KEY (`car_wash_id_car_wash`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
